# Generated by Django 3.2.13 on 2022-11-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=10)),
                ('dislike_movies', models.ManyToManyField(related_name='dislike_choices', to='movies.Movie')),
                ('like_movies', models.ManyToManyField(related_name='like_choices', to='movies.Movie')),
                ('option_movies', models.ManyToManyField(related_name='option_choices', to='movies.Movie')),
            ],
        ),
    ]
